### PR TITLE
Add optional setHeight prop to set height of the container after reposition

### PR DESCRIPTION
**Pull request by mediabakery**

### CODE REVIEW

**Comment by MarimuthuMeenakshisundaram** [comment]
Hi Mediabakery,
When will these changes will be merged as a new version?

**Comment by rexxars** [comment]
Released in 0.2.2. Sorry about the (very long) wait.

**Comment by MarimuthuMeenakshisundaram** [comment]
Hi Rexxars,
After this release 0.2.2, i am getting the issue "Cannot read property 'getBoundingClientRect' of undefined".

**Comment by manimuthukumar6** [comment]
Hi Rexxars,
After the update 0.2.2, I am also getting same the issue "Cannot read property 'getBoundingClientRect' of undefined".

**Pull request merged**
